# Pandas String Methods

This notebook is a **conceptual and practical reference** for two essential Pandas string methods:

- `.str.contains()` → filtering text data using patterns
- `.str.replace()` → cleaning and transforming text data

The goal is **understanding usage**, not memorizing regex syntax.

## Why Pandas String Methods?

In real datasets, text columns often contain:
- currency symbols
- extra spaces
- inconsistent wording
- numbers embedded in text

Pandas provides the `.str` accessor to apply **string operations column-wise**.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'text': [
        'In stock (22 available)',
        'Out of stock',
        'In stock (5 available)',
        'Only 1 left in stock'
    ]
})

df

                      text
0  In stock (22 available)
1             Out of stock
2   In stock (5 available)
3     Only 1 left in stock

## Filtering Rows

`.str.contains()` checks whether a **pattern exists** in each value of a column.

**Typical use cases:**
- keep rows containing a keyword
- exclude rows based on text
- filter data before analysis

In [8]:
df.head()

                      text
0  In stock (22 available)
1             Out of stock
2   In stock (5 available)
3     Only 1 left in stock

In [7]:
df[df['text'].str.contains('In stock')]

                      text
0  In stock (22 available)
2   In stock (5 available)

In [5]:
# Keep rows containing 'In stock'
df[df['text'].str.lower().str.contains('in stock')]

                      text
0  In stock (22 available)
2   In stock (5 available)
3     Only 1 left in stock

### Case sensitivity

By default, `.str.contains()` is **case-sensitive**.

In [9]:
df[df['text'].str.contains('in stock', case=False)]

                      text
0  In stock (22 available)
2   In stock (5 available)
3     Only 1 left in stock

### Handling missing values

If a column contains `NaN`, use `na=False` to avoid errors.

In [14]:
df[df['text'].str.contains(r'\(.*\)', na=False, regex=True)]

                      text
0  In stock (22 available)
2   In stock (5 available)

In [13]:
df[df['text'].str.contains('stock', na=False)]

                      text
0  In stock (22 available)
1             Out of stock
2   In stock (5 available)
3     Only 1 left in stock

## Cleaning Text

`.str.replace()` replaces parts of strings using **literal text or regex patterns**.

**Typical use cases:**
- remove currency symbols
- delete unwanted characters
- standardize text formats

In [18]:
# Remove parentheses and their content
df['clean_text'] = df['text'].str.replace(r'\(.*\)', '', regex=True)

df['clean_text_2'] = df['text'].str.replace('In stock', 'in stock', regex=False)

df

                      text            clean_text             clean_text_2
0  In stock (22 available)             In stock   in stock (22 available)
1             Out of stock          Out of stock             Out of stock
2   In stock (5 available)             In stock    in stock (5 available)
3     Only 1 left in stock  Only 1 left in stock     Only 1 left in stock

### Replacing literal text

Regex is optional — for simple replacements it can be disabled.

In [24]:
df["number"] = "22"

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   text          4 non-null      object
 1   clean_text    4 non-null      object
 2   clean_text_2  4 non-null      object
 3   number        4 non-null      object
dtypes: object(4)
memory usage: 260.0+ bytes

In [ ]:
df['standardized'] = df['text'].str.replace('Out of stock', 'Unavailable', regex=False)
df

## Common Regex Patterns

Some **very common patterns** you will see in practice:

- `\d+` → one or more digits
- `\(.*\)` → text inside parentheses
- `[^0-9]` → anything that is NOT a digit

In [22]:
df["text"].str

In [21]:
df["text"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: text
Non-Null Count  Dtype
--------------  -----
4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes

In [ ]:
# Extract numbers from text
df['stock_number'] = df['text'].str.replace(r'[^0-9]', '', regex=True)
df

## Summary

| Method | Purpose |
|------|--------|
| `.str.contains()` | Filter rows based on text |
| `.str.replace()` | Modify or clean text values |

**Rule of thumb:**
- Need to **keep or discard rows** → `contains`
- Need to **change text values** → `replace`